program Myloo_Boleto;

uses
  Vcl.Forms,
  ufrmMain in 'ufrmMain.pas' {frmMain},
  Myloo.Base64 in 'Myloo.Base64.pas',
  Myloo.Boleto.BancoAmazonia in 'Myloo.Boleto.BancoAmazonia.pas',
  Myloo.Boleto.BancoBancoob in 'Myloo.Boleto.BancoBancoob.pas',
  Myloo.Boleto.BancoBanese in 'Myloo.Boleto.BancoBanese.pas',
  Myloo.Boleto.BancoBanestes in 'Myloo.Boleto.BancoBanestes.pas',
  Myloo.Boleto.BancoBanrisul in 'Myloo.Boleto.BancoBanrisul.pas',
  Myloo.Boleto.BancoBic in 'Myloo.Boleto.BancoBic.pas',
  Myloo.Boleto.BancoBradesco in 'Myloo.Boleto.BancoBradesco.pas',
  Myloo.Boleto.BancoBradescoSICOOB in 'Myloo.Boleto.BancoBradescoSICOOB.pas',
  Myloo.Boleto.BancoBrasil in 'Myloo.Boleto.BancoBrasil.pas',
  Myloo.Boleto.BancoBrasilSicoob in 'Myloo.Boleto.BancoBrasilSicoob.pas',
  Myloo.Boleto.BancoBRB in 'Myloo.Boleto.BancoBRB.pas',
  Myloo.Boleto.BancoCaixa in 'Myloo.Boleto.BancoCaixa.pas',
  Myloo.Boleto.BancoCaixaSICOB in 'Myloo.Boleto.BancoCaixaSICOB.pas',
  Myloo.Boleto.BancoCecred in 'Myloo.Boleto.BancoCecred.pas',
  Myloo.Boleto.BancoCredisis in 'Myloo.Boleto.BancoCredisis.pas',
  Myloo.Boleto.BancoHSBC in 'Myloo.Boleto.BancoHSBC.pas',
  Myloo.Boleto.BancoItau in 'Myloo.Boleto.BancoItau.pas',
  Myloo.Boleto.BancoMercantil in 'Myloo.Boleto.BancoMercantil.pas',
  Myloo.Boleto.BancoNordeste in 'Myloo.Boleto.BancoNordeste.pas',
  Myloo.Boleto.BancoSafra in 'Myloo.Boleto.BancoSafra.pas',
  Myloo.Boleto.BancoSafraBradesco in 'Myloo.Boleto.BancoSafraBradesco.pas',
  Myloo.Boleto.BancoSantander in 'Myloo.Boleto.BancoSantander.pas',
  Myloo.Boleto.BancoSicredi in 'Myloo.Boleto.BancoSicredi.pas',
  Myloo.Boleto.BancoUnicredES in 'Myloo.Boleto.BancoUnicredES.pas',
  Myloo.Boleto.BancoUnicredRS in 'Myloo.Boleto.BancoUnicredRS.pas',
  Myloo.Boleto.Images.LogoBancoColor in 'Myloo.Boleto.Images.LogoBancoColor.pas',
  Myloo.Boleto.Images.LogoBancoPtoBco in 'Myloo.Boleto.Images.LogoBancoPtoBco.pas',
  Myloo.Boleto in 'Myloo.Boleto.pas',
  Myloo.Boleto.Report.FastReport in 'Myloo.Boleto.Report.FastReport.pas',
  Myloo.Boleto.Report.FastReport.Report in 'Myloo.Boleto.Report.FastReport.Report.pas',
  Myloo.Boleto.Uniprime in 'Myloo.Boleto.Uniprime.pas',
  Myloo.Boleto.Utils in 'Myloo.Boleto.Utils.pas',
  Myloo.Consts in 'Myloo.Consts.pas',
  Myloo.Validador in 'Myloo.Validador.pas',
  Myloo.Compress.GZIPUtils in 'Myloo.Compress.GZIPUtils.pas',
  Myloo.Compress in 'Myloo.Compress.pas',
  Myloo.Images.LogoProtect in 'Myloo.Images.LogoProtect.pas',
  Myloo.Imaging in 'Myloo.Imaging.pas',
  asn1util in 'Synapse\asn1util.pas',
  blcksock in 'Synapse\blcksock.pas',
  clamsend in 'Synapse\clamsend.pas',
  dnssend in 'Synapse\dnssend.pas',
  ftpsend in 'Synapse\ftpsend.pas',
  ftptsend in 'Synapse\ftptsend.pas',
  httpsend in 'Synapse\httpsend.pas',
  imapsend in 'Synapse\imapsend.pas',
  laz_synapse in 'Synapse\laz_synapse.pas',
  ldapsend in 'Synapse\ldapsend.pas',
  mimeinln in 'Synapse\mimeinln.pas',
  mimemess in 'Synapse\mimemess.pas',
  mimepart in 'Synapse\mimepart.pas',
  nntpsend in 'Synapse\nntpsend.pas',
  pingsend in 'Synapse\pingsend.pas',
  pop3send in 'Synapse\pop3send.pas',
  slogsend in 'Synapse\slogsend.pas',
  smtpsend in 'Synapse\smtpsend.pas',
  snmpsend in 'Synapse\snmpsend.pas',
  sntpsend in 'Synapse\sntpsend.pas',
  ssl_cryptlib in 'Synapse\ssl_cryptlib.pas',
  ssl_libssh2 in 'Synapse\ssl_libssh2.pas',
  ssl_openssl in 'Synapse\ssl_openssl.pas',
  ssl_openssl_lib in 'Synapse\ssl_openssl_lib.pas',
  ssl_sbb in 'Synapse\ssl_sbb.pas',
  ssl_streamsec in 'Synapse\ssl_streamsec.pas',
  synachar in 'Synapse\synachar.pas',
  synacode in 'Synapse\synacode.pas',
  synacrypt in 'Synapse\synacrypt.pas',
  synadbg in 'Synapse\synadbg.pas',
  synafpc in 'Synapse\synafpc.pas',
  synaicnv in 'Synapse\synaicnv.pas',
  synaip in 'Synapse\synaip.pas',
  synamisc in 'Synapse\synamisc.pas',
  synaser in 'Synapse\synaser.pas',
  synautil in 'Synapse\synautil.pas',
  synsock in 'Synapse\synsock.pas',
  tlntsend in 'Synapse\tlntsend.pas',
  tzutil in 'Synapse\tzutil.pas',
  Myloo.Mail in 'Myloo.Mail.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
